### PR TITLE
Simple logic optimisations

### PR DESCRIPTION
**Pull request by clemmyn23**
Moved the math-heavy stuff to be pre-calculated on object creation instead. 

Will see what else I can do. :smile:

### CODE REVIEW

**Comment by clemmyn23** [comment]
I tried... I just want to play them technical without stutters :sob: 
- TIL there are hardware implementations for floating point arithmetic (and probably sqrt) on ARMv7 chips...  
- Shuffled some logic around so hopefully the compiler can optimise them.  
- There are some float to Double comparisons at Results.java getAccuracyFor() around line 35. Not sure how you want to handle them.

Are there any better ways to test the app other than playing maps every time?

**Comment by kbz** [comment]
If you want to eliminate stutters, use mp3 files (ogg is poorly optimized for bigger files), and it seems that the playback of sound is what causes the stutters most of the time, even if you use 'Initial Sync' mode, it'll eventually happen. And I don't know the cause for sure.

**Comment by clemmyn23** [comment]
hmmm how annoying. Will look into that tomorrow. Thanks!

**Comment by clemmyn23** [comment]
**Moving this to the issue tracker. [LINK](https://github.com/kbz/SIFTrain/issues/15#issue-120933662)**

---

~~I think I found it. Need a bit more testing though.~~

~~So basically every time the tap sound plays the SoundPool code runs through the permission check in appOps to see if sound playback is allowed. And for whatever reason one of the checks throws an error (which happens quite often as evident in the stutters) it defaults to false (ie. yolo we'll play the sound anyway) while throwing an expensive error.~~

~~This is platform specific to Android since Sound.java implements AndroidSound which uses SoundPool.~~

~~Proposed solution: implement a custom play() method and check appops permission on app load.~~ 

~~Thoughts?~~

**Pull request closed without merging**
